### PR TITLE
Set of minor changes to gdp-hmi autotool package!

### PR DESCRIPTION
**Pull request by thusharams**
Hello,
      Please find some patches for review to improve the AutoMake and autotool usage for this package. The package was built and tested(Not completely, failed to fetch some dependency packages like wayland-client bla bla bla) on Ubuntu 15.10. Looks like my PC is running very(terribly) slow, I will get back to this once my PC is back to track. Thank you

### CODE REVIEW

**Comment by tom--pollard** [comment]
Thanks for this PR @thushigit ! Have you managed to find time to come back and test this completely?

**Comment by thusharams** [comment]
Not yet but the changes which I pushed doesn't really affect any of the existing features. The only thing which was changed is, to build this package one should use `autogen.sh` instead of running the configure script or something else directly( b1a6513). And the other changes are very minor changes. I don't have the Genivi development environment to test it right now and I didn't get any information to setup the same(May be it will be helpful if you/anyone can point me to the right documentation for the same)I did tested this on my native Ubuntu as it is just the build rule changes and it shouldn't really make much difference with the Genivi dev environment. My PC is really sick and it takes some time to get back :(

**Comment by tom--pollard** [comment]
Hi @thushigit 

By dev environment, I presume you mean how we build the genivi-dev-platform?

First of all take a look at the README here:

https://github.com/GENIVI/genivi-dev-platform

This should highlight everything you would need to get going

**Comment by thusharams** [comment]
Ok development environment I mean, Where you build and run this particular package(gdp-hmi) on your host machine/development machine(for development and testing, instead of directly build and running it for a specific target)? For example, I will just build this package on my Ubuntu distribution(x86) and test it during development. Instead the Genivi provides something to build its own packages(something like a rootfs or a distribution itself). Thanks for the link, I will have a look at that.

**Comment by gunnarx** [comment]
If you mean the HMI specifically:  since it is Qt/QML based, typically you can often run the HMI by loading the project in Qt Creator on your host machine.  Have not tried it.  Might need some tweaking.

For SDK question in general we can provide you with some more clear information but I think the mailing list is a better forum than this pull-request to continue the general discussion on development environment.

**Comment by gunnarx** [comment]
This PR will need integration into the GDP Yocto build if it is going to succeed.  Tom knows that, but just for the record.  

Trying something out in Ubuntu, and making the software work better in such environments is great, but is not sufficient for acceptance since Yocto is our current main build environment for GDP.

So the next question is how to modify the .bb recipes accordingly, and to test compilation as well as function.

**Comment by thusharams** [comment]
@gunnarx Since I am not so familiar with the GDP Yocto build and still I am setting up the required things on my PC(Honestly it takes some time for me to understand and set it up, and I guess it is a one time effort). We can keep this in hold till I get the setup or if someone familiar building these changes with the Yocto build, they can take it up.

**Pull request closed without merging**
